message = ('jaden')
print(message)
message = ('loves')
print(message)
message = ('harley')
print(message)
message =('Jaden')
print(message)
message =('Loves')
print(message)
message = ('Harley')
print(message)
print(message)
print(message)
message = ('jaden loves harley')
print (message)
message = ('[2, 3, 4, 5]')
print(message)
message = ('[14]')
print(message)
message = ('jaden loves harley [14]')
print(message)
numbers = [1, 2, 3, 3, 4, 5,]
print(numbers)
print(1+2+3+3+4+5)
print(18/6)
answer = (18/6)

for x in numbers: 
    print(numbers)
    